# Chinese translations for Rubisco package
# Rubisco 软件包的简体中文翻译.
# Copyright (C) 2024 The C++ Plus Project.
# This file is part of the Rubisco.
#
# Rubisco is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# Rubisco is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
msgid ""
msgstr ""
"Project-Id-Version: Rubisco 0.1.0\n"
"Report-Msgid-Bugs-To: cpppteam@email.cn\n"
"POT-Creation-Date: 2025-03-31 23:07+0800\n"
"PO-Revision-Date: 2024-06-25 11:07+0800\n"
"Last-Translator:  <wushengwuxi-msctinoulk@outlook.com>\n"
"Language-Team: Chinese (simplified) <i18n-zh@googlegroups.com>\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: /usr/lib/python3.12/argparse.py:736
#, python-format
msgid " (default: %(default)s)"
msgstr " （默认值：%(default)s）"

#: ../rubisco/cli/main/ktrigger.py:308
msgid "${{speed}} us"
msgstr "${{speed}} 微秒"

#: /usr/lib/python3.12/argparse.py:242
#, python-format
msgid "%(heading)s:"
msgstr "%(heading)s:"

#: /usr/lib/python3.12/argparse.py:2664
#, python-format
msgid "%(prog)s: error: %(message)s\n"
msgstr "%(prog)s: 错误: %(message)s\n"

#: /usr/lib/python3.12/argparse.py:2555
#, python-format
msgid "%r is not callable"
msgstr "%r 不是可调用的"

#: ../rubisco/shared/ktrigger.py:602
msgid "'${{name}}' is not a IKernelTrigger instance."
msgstr "'${{name}}' 不是 IKernelTrigger 实例。"

#: ../rubisco/envutils/packages.py:117
msgid "'${{name}}' package contains files that not allowed in the root directory."
msgstr "'${{name}}' 软件包包含不允许在根目录中的文件。"

#: ../rubisco/envutils/packages.py:100
msgid "'${{name}}' package must contain a directory with the same name as the package name and a 'rubisco.json' file."
msgstr "'${{name}}' 软件包必须包含一个与软件包名称相同的目录和一个 'rubisco.json' 文件。"

#: ../rubisco/cli/main/project_config.py:146
msgid "'[underline]${{path}}[/underline]' is not found."
msgstr "未找到 '[underline]${{path}}[/underline]'。"

#: ../rubisco/lib/archive/utils.py:90
msgid "'[underline]${{path}}[/underline]' is not in the subpath of '[underline]${{start}}[/underline]'"
msgstr "'[underline]${{path}}[/underline]' 不在 '[underline]${{start}}[/underline]' 的子路径中"

#: /usr/lib/python3.12/argparse.py:1597
msgid "'required' is an invalid argument for positionals"
msgstr "'required' 是位置参数的无效参数"

#: ../rubisco/cli/main/project_config.py:99 ../rubisco/cli/main/ktrigger.py:503
msgid "(${{num}} hooks)"
msgstr "(${{num}} 个钩子)"

#: /usr/lib/python3.12/argparse.py:904
msgid ".__call__() not defined"
msgstr ".__call__() 未定义"

#: ../rubisco/lib/sqlite_strerror.py:187
msgid "2nd parameter to sqlite3_bind out of range."
msgstr "第二个参数超出范围。"

#: ../rubisco/kernel/workflow.py:898
msgid "<Inline Workflow>"
msgstr "<内联工作流>"

#: ../rubisco/kernel/project_config.py:170 ../rubisco/kernel/workflow.py:160
#: ../rubisco/kernel/workflow.py:776 ../rubisco/kernel/workflow.py:777
msgid "<Unnamed>"
msgstr "<未命名>"

#: ../rubisco/lib/sqlite_strerror.py:227
msgid "A CHECK constraint failed."
msgstr "一个 CHECK 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:322
msgid "A NOT NULL constraint failed."
msgstr "一个 NOT NULL 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:340
msgid "A PRIMARY KEY constraint failed."
msgstr "一个 PRIMARY KEY 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:349
msgid "A RAISE function within a trigger fired, causing the SQL statement to abort."
msgstr "一个触发器中的 RAISE 函数触发，导致 SQL 语句中止。"

#: ../rubisco/lib/sqlite_strerror.py:358
msgid "A UNIQUE constraint failed."
msgstr "一个 UNIQUE 约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:212
msgid "A WAL mode database cannot be opened because the database file needs to be recovered and recovery requires write access but only read access is available."
msgstr "一个 WAL 模式数据库无法打开，因为数据库文件需要恢复，而恢复需要写访问权限，但只有读访问权限可用。"

#: ../rubisco/lib/sqlite_strerror.py:242
msgid "A WAL mode database connection tries to promote a read transaction into a write transaction but finds that another database connection has already written to the database and thus invalidated prior reads."
msgstr "一个 WAL 模式数据库连接试图将一个读事务提升为写事务，但发现另一个数据库连接已经写入了数据库，从而使之前的读取无效。"

#: ../rubisco/lib/sqlite_strerror.py:234
msgid "A WAL mode database file has been recovered."
msgstr "一个 WAL 模式数据库文件已经恢复。"

#: ../rubisco/lib/sqlite_strerror.py:278
msgid "A blocking POSIX advisory file lock request in the VFS layer failed due to a timeout."
msgstr "一个在 VFS 层的阻塞 POSIX 咨询文件锁请求由于超时而失败。"

#: ../rubisco/lib/sqlite_strerror.py:271
msgid "A commit hook callback returned non-zero that thus caused the SQL statement to be rolled back."
msgstr "一个提交钩子回调返回了非零值，导致 SQL 语句被回滚。"

#: ../rubisco/lib/sqlite_strerror.py:303
msgid "A database cannot be modified because the database file has been moved since it was opened."
msgstr "数据库无法修改，因为数据库文件在打开后已经移动。"

#: ../rubisco/lib/sqlite_strerror.py:283
msgid "A database cannot be opened because it has a hot journal that needs to be rolled back but cannot because the database is readonly."
msgstr "数据库无法打开，因为它有一个需要回滚的热日志，但无法回滚，因为数据库是只读的。"

#: ../rubisco/lib/sqlite_strerror.py:267
msgid "A file failed to open because the file is really a directory."
msgstr "文件打开失败，因为文件实际上是一个目录。"

#: ../rubisco/lib/sqlite_strerror.py:296
msgid "A file open operation failed because the operating system was unable to convert the filename into a full pathname."
msgstr "文件打开操作失败，因为操作系统无法将文件名转换为完整路径名。"

#: ../rubisco/lib/sqlite_strerror.py:300
msgid "A foreign key constraint failed."
msgstr "一个外键约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:313
msgid "A function constraint failed."
msgstr "一个函数约束失败。"

#: ../rubisco/lib/sqlite_strerror.py:260
msgid "A read attempt in the VFS layer was unable to obtain as many bytes as was requested."
msgstr "VFS 层的读取尝试无法获得所请求的字节数。"

#: ../rubisco/lib/sqlite_strerror.py:367
msgid "A rowid is not unique."
msgstr "一个 rowid 不是唯一的。"

#: ../rubisco/lib/sqlite_strerror.py:467
msgid "A seek or read failure was due to the request not falling within the file's boundary rather than an ordinary device failure."
msgstr "寻找或读取失败是由于请求不在文件的边界内，而不是普通的设备故障。"

#: ../rubisco/lib/sqlite_strerror.py:149
msgid "A table in the database is locked."
msgstr "数据库中的一个表被锁定。"

#: ../rubisco/kernel/project_config.py:91
msgid "A workflow [yellow]SHOULD[/yellow] contain at least 'exec', 'run' and 'workflow'."
msgstr "工作流 [yellow]应该[/yellow]至少包含 'exec'， 'run' 和 'workflow' 选项。"

#: ../rubisco/kernel/workflow.py:718
msgid "A workflow step must be a dict."
msgstr "工作流步骤必须是一个字典。"

#: ../rubisco/lib/sqlite_strerror.py:174
msgid "Abort due to constraint violation."
msgstr "由于约束违规而中止。"

#: ../rubisco/lib/fileutil.py:90
msgid "Absolute path '[underline]${{path}}[/underline]' is not allowed."
msgstr "不允许使用绝对路径 '[underline]${{path}}[/underline]'。"

#: ../rubisco/lib/sqlite_strerror.py:143
msgid "Access permission denied."
msgstr "访问权限被拒绝。"

#: ../rubisco/lib/sqlite_strerror.py:206
msgid "Access to an SQLite data record is blocked by another database connection that is using the same record in shared cache mode."
msgstr "另一个数据库连接正在使用共享缓存模式中的相同记录，阻止对 SQLite 数据记录的访问。"

#: ../rubisco/kernel/mirrorlist.py:194
msgid "All mirrors are unreachable or canceled. Switching to official [underline][blue]${{url}}[/blue][/underline] ..."
msgstr "所有镜像都无法访问或已取消。切换到 official [underline][blue]${{url}}[/blue][/underline] ..."

#: ../rubisco/lib/sqlite_strerror.py:308 ../rubisco/lib/sqlite_strerror.py:316
msgid "An I/O error occured in the VFS layer while trying to fsync."
msgstr "尝试 fsync 时发 VFS 层中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:343
msgid "An I/O error occured in the VFS layer while trying to invoke fstat() (or the equivalent) on a file in order to determine information such as the file size or access permissions."
msgstr "尝试调用 fstat()（或等效函数）以确定文件大小或访问权限等信息时，VFS 层中发生了 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:289
msgid "An I/O error occured in the VFS layer while trying to write into a file on disk."
msgstr "尝试在磁盘上的文件中写入时，VFS 层中发生了 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:354
msgid "An I/O error within xUnlock method on the sqlite3_io_methods object."
msgstr "一个 sqlite3_io_methods 对象上的 xUnlock 方法中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:237
msgid "An SQL statement aborted because the transaction that was active when the SQL statement first started was rolled back."
msgstr "一个 SQL 语句中止，因为在 SQL 语句首次启动时活动的事务被回滚。"

#: ../rubisco/lib/sqlite_strerror.py:196
msgid "An SQL statement could not be prepared because a collating sequence named in that SQL statement could not be located."
msgstr "一个 SQL 语句无法准备，因为在该 SQL 语句中命名的排序序列无法找到。"

#: ../rubisco/lib/sqlite_strerror.py:373
msgid "An UPDATE trigger attempted do delete the row that was being updated in the middle of the update."
msgstr "一个 UPDATE 触发器尝试在更新过程中删除正在更新的行。"

#: ../rubisco/lib/sqlite_strerror.py:378
msgid "An operation could not be completed due to the inability to allocate sufficient memory."
msgstr "由于无法分配足够的内存，无法完成操作。"

#: ../rubisco/lib/sqlite_strerror.py:193
msgid "An operation is completed."
msgstr "操作已完成。"

#: ../rubisco/lib/sqlite_strerror.py:230
msgid "An operation was attempted on a database for which the logged in user lacks sufficient authorization."
msgstr "尝试对一个数据库进行操作，但登录的用户缺乏足够的授权。"

#: ../rubisco/lib/sqlite_strerror.py:191
msgid "Another row of output is available."
msgstr "另一行输出可用。"

#: ../rubisco/lib/sqlite_strerror.py:153
msgid "Attempt to write a readonly database."
msgstr "尝试写入只读数据库。"

#: ../rubisco/cli/main/arg_parser.py:108
msgid "Available commands"
msgstr "可用命令"

#: ../rubisco/lib/sqlite_strerror.py:145
msgid "Callback routine requested an abort."
msgstr "回调例程请求中止。"

#: ../rubisco/kernel/project_config.py:299
msgid "Circular dependency detected: [underline]${{path}}[/underline]."
msgstr "检测到循环依赖：[underline]${{path}}[/underline]。"

#: ../rubisco/cli/main/ktrigger.py:255
msgid "Cloning Git repository ${{url}} (${{branch}}) into '[underline]${{path}}[/underline]' ..."
msgstr "正在克隆 Git 仓库 ${{url}} (${{branch}}) 到 '[underline]${{path}}[/underline]' ..."

#: ../rubisco/lib/fileutil.py:668
msgid "Command '${{cmd}}' not found."
msgstr "命令 '${{cmd}}' 未找到。"

#: ../rubisco/kernel/workflow.py:552
msgid "Compress format must be a list of string or a string."
msgstr "压缩格式必须是字符串或字符串列表。"

#: ../rubisco/lib/archive/zip.py:129 ../rubisco/lib/archive/__init__.py:330
#: ../rubisco/lib/archive/tar.py:156 ../rubisco/lib/archive/sevenzip.py:193
msgid "Compressing '[underline]${{path}}[/underline]' to '[underline]${{file}}[/underline]' as '${{type}}' ..."
msgstr "正在以 '${{type}}' 格式压缩 '[underline]${{path}}[/underline]' 到 '[underline]${{file}}[/underline]' ..."

#: ../rubisco/kernel/project_config.py:272
msgid "Configuration must be a JSON5 object. (dict)"
msgstr "配置必须是 JSON5 对象。 (dict)"

#: ../rubisco/kernel/workflow.py:762
msgid "Consider use 'type' attribute manually."
msgstr "考虑手动指定 'type' 属性。"

#: ../rubisco/lib/sqlite_strerror.py:222
msgid "Content in the virtual table is corrupt."
msgstr "虚拟表中的内容损坏。"

#: ../rubisco/cli/main/ktrigger.py:231
msgid "Continue anyway?"
msgstr "仍然继续吗？"

#: ../rubisco/cli/main/ktrigger.py:808
msgid "Continue?"
msgstr "是否继续？"

#: ../rubisco/cli/main/ktrigger.py:407
msgid "Copying '[underline]${{src}}[/underline]' to '[underline]${{dst}}[/underline]' ..."
msgstr "正在复制 '[underline]${{src}}[/underline]' 到 '[underline]${{dst}}[/underline]' ..."

#: ../rubisco/cli/main/version_action.py:42
msgid ""
"Copyright (C) 2024 The C++ Plus Project.\n"
"License [bold]GPLv3+[/bold]: GNU GPL version [cyan]3[/cyan] or later <https://www.gnu.org/licenses/gpl.html>.\n"
"This is free software: you are free to change and redistribute it.\n"
"There is [yellow]NO WARRANTY[/yellow], to the extent permitted by law.\n"
"Written by [underline]ChenPi11[/underline]."
msgstr ""
"版权 (C) 2024 The C++ Plus Project.\n"
"许可证 [bold]GPLv3+[/bold]：GNU GPL 许可证第[cyan]三[/cyan]版或者更新版本 <http://gnu.org/licenses/gpl.html>.\n"
"这是自由软件：你可以自由更改和重新发布它。\n"
"在法律许可的情况下特此明示，本软件[yellow]不提供任何担保[/yellow]。"
"由 [underline]ChenPi11[/underline] 编写。"

#: ../rubisco/cli/main/ktrigger.py:381
msgid "Creating directory: [underline]${{path}}[/underline] ..."
msgstr "创建目录： [underline]${{path}}[/underline] ..."

#: ../rubisco/cli/main/ktrigger.py:533
msgid "Creating hard link: [underline]${{src}}[/underline] -> '[underline]${{dst}}[/underline]'..."
msgstr "正在创建硬链接： [underline]${{src}}[/underline] -> '[underline]${{dst}}[/underline]'..."

#: ../rubisco/cli/main/ktrigger.py:520
msgid "Creating symbolic link: [underline]${{src}}[/underline] -> '[underline]${{dst}}[/underline]'..."
msgstr "正在创建符号链接： [underline]${{src}}[/underline] -> '[underline]${{dst}}[/underline]'..."

#: ../rubisco/envutils/env.py:463 ../rubisco/cli/main/ktrigger.py:546
msgid "Creating venv: '[underline]${{path}}[/underline]' ..."
msgstr "正在创建 venv： '[underline]${{path}}[/underline]'..."

#: ../rubisco/lib/sqlite_strerror.py:176
msgid "Data type mismatch."
msgstr "数据类型不匹配。"

#: ../rubisco/lib/sqlite_strerror.py:165
msgid "Database file is malformed."
msgstr "数据库文件格式错误。"

#: ../rubisco/cli/main/extman_cmds.py:181
msgid "Description: ${{desc}}"
msgstr "描述： ${{desc}}"

#: ../rubisco/lib/wget.py:70
msgid "Downloading ${{url}} ..."
msgstr "正在下载 ${{url}} ..."

#: ../rubisco/cli/main/main.py:73
msgid "Entering directory '${{path}}' ..."
msgstr "进入目录 '${{path}}'..."

#: ../rubisco/lib/fileutil.py:127
msgid "Error while removing '[underline]${{path}}[/underline]': ${{error}}"
msgstr "删除 '[underline]${{path}}[/underline]' 时出错： ${{error}}"

#: ../rubisco/cli/main/ktrigger.py:99
msgid "Executing: [cyan]${{cmd}}[/cyan] ..."
msgstr "正在执行： [cyan]${{cmd}}[/cyan] ..."

#: ../rubisco/cli/main/ktrigger.py:428
msgid "Extension '${{name}}' loaded."
msgstr "扩展 '${{name}}' 已加载。"

#: ../rubisco/envutils/packages.py:435
msgid "Extension '${{name}}'([underline]${{path}}[/underline]) not found in the filesystem."
msgstr "扩展 '${{name}}'([underline]${{path}}[/underline]) 未在文件系统中找到。"

#: ../rubisco/cli/main/ktrigger.py:616
msgid "Extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] was successfully installed."
msgstr "扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 已成功安装。"

#: ../rubisco/cli/main/ktrigger.py:688
msgid "Extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] was successfully uninstalled."
msgstr "扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 已成功卸载。"

#: ../rubisco/cli/main/ktrigger.py:760
msgid "Extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] was successfully upgraded."
msgstr "扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 已成功升级。"

#: ../rubisco/cli/main/arg_parser.py:125
msgid "Extension commands."
msgstr "扩展命令。"

#: ../rubisco/cli/main/extman_cmds.py:374
msgid "Extension package files glob patterns."
msgstr "扩展包文件 glob 模式字符串。"

#: ../rubisco/lib/archive/zip.py:64 ../rubisco/lib/archive/__init__.py:115
#: ../rubisco/lib/archive/tar.py:77 ../rubisco/lib/archive/sevenzip.py:56
msgid "Extracting '[underline]${{file}}[/underline]' to '[underline]${{path}}[/underline]' as '${{type}}' ..."
msgstr "正在以 '${{type}}' 格式解压 '[underline]${{file}}[/underline]' 到 '[underline]${{path}}[/underline]' ..."

#: ../rubisco/envutils/utils.py:78
msgid "Failed to add '${{path}}' to sys.path: ${{exc}}"
msgstr "将 '${{path}}' 添加到 sys.path 时出错： ${{exc}}"

#: ../rubisco/envutils/env.py:124
msgid "Failed to check the environment."
msgstr "检查环境时出错。"

#: ../rubisco/lib/archive/__init__.py:533
msgid "Failed to compress '${{src}}' to '${{dest}}': '${{exc}}'"
msgstr "压缩 '${{src}}' 到 '${{dest}}' 失败： '${{exc}}'"

#: ../rubisco/envutils/env.py:156
msgid "Failed to create the database for the environment."
msgstr "创建环境数据库时出错。"

#: ../rubisco/envutils/env.py:148
msgid "Failed to create venv. Consider to check thepermissions of the path."
msgstr "创建 venv 时出错。请检查路径的权限。"

#: ../rubisco/lib/archive/__init__.py:270
msgid "Failed to extract '${{file}}' to '${{dest}}': '${{exc}}'"
msgstr "解压 '${{file}}' 到 '${{dest}}' 失败： '${{exc}}'"

#: ../rubisco/shared/extension.py:290
msgid "Failed to load extension '${{name}}': ${{exc}}."
msgstr "加载扩展 '${{name}}' 失败： ${{exc}}。"

#: ../rubisco/shared/extension.py:204
msgid "Failed to load extension '[underline]${{path}}[/underline]'."
msgstr "加载扩展 '[underline]${{path}}[/underline]' 失败。"

#: ../rubisco/envutils/env_db.py:154
msgid "Failed to open or operate on database '[underline]${{path}}[/underline]': ${{exc}}"
msgstr "打开或操作数据库 '[underline]${{path}}[/underline]' 失败： ${{exc}}"

#: ../rubisco/envutils/env.py:326
msgid "Failed to read the lock file '[underline]${{path}}[/underline]': ${{msg}}"
msgstr "读取锁文件 '[underline]${{path}}[/underline]' 失败： ${{msg}}"

#: ../rubisco/envutils/env.py:406
msgid "Failed to unlock the extension environment '${{path}}': ${{msg}}"
msgstr "解锁扩展环境 '${{path}}' 失败： ${{msg}}"

#: ../rubisco/lib/fileutil.py:241
msgid "File '[underline]${{path}}[/underline]' already exists."
msgstr "文件 '[underline]${{path}}[/underline]' 已经存在。"

#: ../rubisco/cli/main/ktrigger.py:120
msgid "File '[underline]${{path}}[/underline]' already exists. [yellow]Overwrite[/yellow]?"
msgstr "文件 '[underline]${{path}}[/underline]' 已经存在。 [yellow]是否覆盖[/yellow]？"

#: ../rubisco/lib/sqlite_strerror.py:189
msgid "File opened that is not a database file."
msgstr "打开的文件不是数据库文件。"

#: ../rubisco/lib/sqlite_strerror.py:218
msgid "Hardware malfunction or a filesystem came unmounted while the file was open."
msgstr "硬件故障或文件系统在文件打开时卸载。"

#: ../rubisco/cli/main/extman_cmds.py:160
msgid "Homepage: ${{homepage}}"
msgstr "主页： ${{homepage}}"

#: ../rubisco/kernel/project_config.py:87
msgid "Hook '${{name}}' is invalid."
msgstr "无效的钩子 '${{name}}' 。"

#: ../rubisco/kernel/project_config.py:198
msgid "Hooks must be a dictionary."
msgstr "钩子必须是一个字典。"

#: ../rubisco/lib/sqlite_strerror.py:332
msgid "I/O error in the VFS layer while trying to truncate a file to a smaller size."
msgstr "在尝试将文件截断为较小大小时，VFS 层中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:392
msgid "I/O error in the advisory file locking logic."
msgstr "咨询文件锁定逻辑中的 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:383
msgid "I/O error occured within the xAccess method on the sqlite3_vfs object."
msgstr "在 sqlite3_vfs 对象上的 xAccess 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:388
msgid "I/O error within the xCheckReservedLock method on the sqlite3_io_methods object."
msgstr "在 sqlite3_io_methods 对象上的 xCheckReservedLock 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:395
msgid "I/O error within the xClose method on the sqlite3_io_methods object."
msgstr "在 sqlite3_io_methods 对象上的 xClose 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:437
msgid "I/O error within the xFetch or xUnfetch methods on the sqlite3_io_methods object while trying to map or unmap part of the database file into the process address space."
msgstr "在尝试将数据库文件的一部分映射或取消映射到进程地址空间时，sqlite3_io_methods 对象上的 xFetch 或 xUnfetch 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:425
msgid "I/O error within the xRead or xWrite methods on the sqlite3_io_methods object while trying to seek a file descriptor to the beginning point of the file where the read or write is to occur."
msgstr "在尝试将文件描述符定位到读取或写入的文件的起始点时，sqlite3_io_methods 对象上的 xRead 或 xWrite 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:409
msgid "I/O error within the xShmMap method on the sqlite3_io_methods object while trying to enlarge a \"shm\" file as part of WAL mode transaction processing. This error may indicate that the underlying filesystem volume is out of space."
msgstr "在尝试在 WAL 模式事务处理的一部分中扩大 \"shm\" 文件时，sqlite3_io_methods 对象上的 xShmMap 方法中发生 I/O 错误。此错误可能表示底层文件系统卷空间不足。"

#: ../rubisco/lib/sqlite_strerror.py:419
msgid "I/O error within the xShmMap method on the sqlite3_io_methods object while trying to map a shared memory segment into the process address space."
msgstr "在尝试将共享内存段映射到进程地址空间时，sqlite3_io_methods 对象上的 xShmMap 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:403
msgid "I/O error within the xShmMap method on the sqlite3_io_methods object while trying to open a new shared memory segment."
msgstr "在尝试打开一个新的共享内存段时，sqlite3_io_methods 对象上的 xShmMap 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:365
msgid "I/O error within xDelete method on the sqlite3_vfs object."
msgstr "在 sqlite3_vfs 对象上的 xDelete 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:361
msgid "I/O error within xLock method on the sqlite3_io_methods object while trying to obtain a read lock."
msgstr "在尝试获取读锁时，sqlite3_io_methods 对象上的 xLock 方法中发生 I/O 错误。"

#: ../rubisco/lib/sqlite_strerror.py:157
msgid "I/O error."
msgstr "输入/输出错误。"

#: ../rubisco/lib/sqlite_strerror.py:182
msgid "Illegal authorization request."
msgstr "非法的授权请求。"

#: ../rubisco/lib/sqlite_strerror.py:161
msgid "Insertion failed because database is full."
msgstr "插入失败，因为数据库已满。"

#: ../rubisco/cli/main/extman_cmds.py:404
msgid "Install extensions to global."
msgstr "在全局安装扩展。"

#: ../rubisco/cli/main/extman_cmds.py:395
msgid "Install extensions to user."
msgstr "在用户安装扩展。"

#: ../rubisco/cli/main/extman_cmds.py:386
msgid "Install extensions to workspace."
msgstr "在工作区安装扩展。"

#: ../rubisco/cli/main/extman_cmds.py:367
msgid "Install extensions with matching patterns."
msgstr "使用匹配模式安装扩展。"

#: ../rubisco/cli/main/extman_cmds.py:146
msgid "Installation Location: ${{loc}}"
msgstr "安装位置： ${{loc}}"

#: ../rubisco/cli/main/ktrigger.py:562
msgid "Installing extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] to global ([underline]${{path}}[/underline]) ..."
msgstr "正在安装扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 到全局 ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/main/ktrigger.py:577
msgid "Installing extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] to user ([underline]${{path}}[/underline]) ..."
msgstr "正在安装扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 到用户 ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/main/ktrigger.py:592
msgid "Installing extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] to workspace ([underline]${{path}}[/underline]) ..."
msgstr "正在安装扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 到工作区 ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/output.py:274
msgid "Internal error: ${{type}}: ${{msg}}"
msgstr "内部错误： ${{type}}： ${{msg}}"

#: ../rubisco/lib/sqlite_strerror.py:141
msgid "Internal logic error in SQLite."
msgstr "SQLite 内部逻辑错误。"

#: ../rubisco/envutils/packages.py:480 ../rubisco/cli/output.py:254
msgid "Interrupted by user."
msgstr "被用户中断。"

#: ../rubisco/kernel/project_config.py:267
msgid "Invalid configuration in file '[underline]${{path}}[/underline]'."
msgstr "文件 '[underline]${{path}}[/underline]' 中的配置无效。"

#: ../rubisco/shared/extension.py:237
msgid "Invalid extension name: '${{name}}' ."
msgstr "无效的扩展名: '${{name}}' 。"

#: ../rubisco/cli/input.py:78
msgid "Invalid input."
msgstr "无效的输入。"

#: ../rubisco/kernel/project_config.py:279
msgid "Invalid path '[underline]${{path}}[/underline]'."
msgstr "无效的路径 '[underline]${{path}}[/underline]'。"

#: ../rubisco/envutils/env_db.py:290
msgid "Invalid regex pattern: '${{pattern}}'."
msgstr "无效的正则表达式: '${{pattern}}'。"

#: ../rubisco/lib/fileutil.py:558
msgid "Invalid type: '${{path}}', expected directory."
msgstr "'${{path}}' 的类型无效，应为目录。"

#: ../rubisco/lib/fileutil.py:548
msgid "Invalid type: '${{path}}', expected file."
msgstr "'${{path}}' 的类型无效，应为文件。"

#: ../rubisco/cli/output.py:260
msgid "Is may caused by a invalid JSON5 configuration file."
msgstr "可能是由于无效的 JSON5 配置文件。"

#: ../rubisco/cli/output.py:268
msgid "Is may caused by a invalid configuration file."
msgstr "可能是由于无效的配置文件。"

#: ../rubisco/cli/output.py:258
msgid "JSON5 decode error."
msgstr "JSON5 解码错误。"

#: ../rubisco/shared/ktrigger.py:610
msgid "Kernel trigger id '${{name}}' is already exists."
msgstr "Kernel trigger ID '${{name}}' 已经存在。"

#: ../rubisco/lib/sqlite_strerror.py:178
msgid "Library used incorrectly."
msgstr "库使用不正确。"

#: ../rubisco/cli/main/extman_cmds.py:167
msgid "License: ${{license}}"
msgstr "许可证： ${{license}}"

#: ../rubisco/cli/main/extman_cmds.py:319
#: ../rubisco/cli/main/extman_cmds.py:361
msgid "List extensions in global."
msgstr "列出全局扩展。"

#: ../rubisco/cli/main/extman_cmds.py:309
#: ../rubisco/cli/main/extman_cmds.py:352
msgid "List extensions in user."
msgstr "列出用户扩展。"

#: ../rubisco/cli/main/extman_cmds.py:299
#: ../rubisco/cli/main/extman_cmds.py:343
msgid "List extensions in workspace."
msgstr "列出工作区扩展。"

#: ../rubisco/cli/main/extman_cmds.py:280
msgid "List extensions with matching patterns."
msgstr "列出匹配模式的扩展。"

#: ../rubisco/envutils/packages.py:165
msgid "Maintainers must be a list of strings."
msgstr "Maintainers 必须是字符串列表。"

#: ../rubisco/envutils/packages.py:170
msgid "Maintainers must not contain ','."
msgstr "Maintainers 不能包含 ','。"

#: ../rubisco/cli/main/extman_cmds.py:153
msgid "Maintainers: ${{maintainers}}"
msgstr "维护者： ${{maintainers}}"

#: ../rubisco/cli/main/arg_parser.py:117
msgid "Manage extensions."
msgstr "管理扩展。"

#: ../rubisco/lib/sqlite_strerror.py:151
msgid "Memory allocation/reallocation failed."
msgstr "内存分配/重新分配失败。"

#: ../rubisco/cli/output.py:264
msgid "Missing key: ${{msg}}"
msgstr "找不到字典的键： ${{msg}}"

#: ../rubisco/cli/main/ktrigger.py:393
msgid "Moving file '[underline]${{src}}[/underline]' to '[underline]${{dst}}[/underline]' ..."
msgstr "正在移动文件 '[underline]${{src}}[/underline]' 到 '[underline]${{dst}}[/underline]' ..."

#: ../rubisco/envutils/packages.py:276
msgid "Multiple instances of '${{name}}' extension found in the database. Selecting the last one."
msgstr "在数据库中找到多个 '${{name}}' 扩展的实例。选择最后一个。"

#: ../rubisco/cli/main/extman_cmds.py:89
msgid "No environment exists or selected."
msgstr "不存在环境或已选择环境。"

#: ../rubisco/envutils/packages.py:401
msgid "No extension found matching '${{pattern}}'."
msgstr "未找到与 '${{pattern}}' 匹配的扩展。"

#: ../rubisco/envutils/packages.py:393
msgid "No extension installed."
msgstr "未安装任何扩展。"

#: ../rubisco/cli/main/extman_cmds.py:243
msgid "No files found."
msgstr "未找到文件。"

#: ../rubisco/lib/sqlite_strerror.py:180
msgid "No large file support."
msgstr "没有大文件支持。"

#: ../rubisco/cli/main/extman_cmds.py:207
msgid "No packages found."
msgstr "未找到软件包。"

#: ../rubisco/lib/sqlite_strerror.py:201
msgid "Operation could not continue because another process is busy recovering a WAL mode database file following a crash."
msgstr "由于另一个进程正在忙于恢复崩溃后的 WAL 模式数据库文件，操作无法继续。"

#: ../rubisco/lib/sqlite_strerror.py:155
msgid "Operation terminated by sqlite3_interrupt()."
msgstr "操作被 sqlite3_interrupt() 终止。"

#: ../rubisco/cli/main/help_formatter.py:59
msgid "Options:"
msgstr "选项："

#: ../rubisco/envutils/packages.py:151
msgid "Package name '${{name}}' invalid."
msgstr "软件包名 '${{name}}' 无效。"

#: ../rubisco/envutils/packages.py:156
msgid "Package name must be lowercase and only contain 0-9, a-z, A-Z, '_', '.' and '-'."
msgstr "软件包名必须是小写的，只能包含 0-9，a-z，A-Z，'_'，'.' 和 '-'。"

#: ../rubisco/cli/main/extman_cmds.py:132
msgid "Package: [green]${{name}}[/green]"
msgstr "软件包： [green]${{name}}[/green]"

#: ../rubisco/cli/main/extman_cmds.py:287
#: ../rubisco/cli/main/extman_cmds.py:332
#: ../rubisco/cli/main/extman_cmds.py:417
msgid "Packages matching patterns."
msgstr "匹配模式的软件包。"

#: ../rubisco/cli/main/ktrigger.py:291
msgid "Performing websites speed test ..."
msgstr "正在进行网站速度测试 ..."

#: ../rubisco/cli/main/project_config.py:123
msgid "Perhaps a typo?"
msgstr "可能是拼写错误？"

#: ../rubisco/kernel/mirrorlist.py:147
msgid "Please check your mirrorlist.json file inworkspace, user or global config directory."
msgstr "请检查您的工作区、用户或全局配置目录中的 mirrorlist.json 文件。"

#: ../rubisco/cli/main/ktrigger.py:224
msgid "Please install the following packages manually: [bold]${{packages}}[/bold]."
msgstr "请手动安装以下软件包： [bold]${{packages}}[/bold]。"

#: ../rubisco/shared/extension.py:211 ../rubisco/shared/extension.py:227
msgid "Please make sure this extension is valid."
msgstr "请确保这个扩展是有效的。"

#: ../rubisco/lib/archive/__init__.py:230
#: ../rubisco/lib/archive/__init__.py:491
msgid "Please specify the compression type explicitly."
msgstr "请明确指定压缩类型。"

#: ../rubisco/kernel/project_config.py:174
msgid "Please upgrade rubisco to the required version."
msgstr "请升级 rubisco 到所需版本。"

#: ../rubisco/shared/extension.py:242
msgid "Please use a different name for the extension."
msgstr "请为扩展使用不同的名称。"

#: ../rubisco/cli/main/help_formatter.py:56
msgid "Positional Arguments:"
msgstr "位置参数："

#: ../rubisco/cli/main/arg_parser.py:45 ../rubisco/cli/main/arg_parser.py:80
msgid "Project root directory."
msgstr "项目根目录。"

#: ../rubisco/cli/main/arg_parser.py:54
msgid "Prompt colors used by rubisco parent process."
msgstr "rubisco 父进程使用的提示颜色。"

#: ../rubisco/kernel/mirrorlist.py:143
msgid "Recursion detected in mirrorlist: '${{name}}'"
msgstr "检测到镜像列表中的递归: '${{name}}'"

#: ../rubisco/cli/main/ktrigger.py:420
msgid "Removing '[underline]${{path}}[/underline]' ..."
msgstr "正在删除 '[underline]${{path}}[/underline]' ..."

#: ../rubisco/kernel/git.py:118
msgid "Repository '[underline]${{path}}[/underline]' already exists."
msgstr "仓库 '[underline]${{path}}[/underline]' 已经存在。"

#: ../rubisco/kernel/git.py:78
msgid "Repository '[underline]${{path}}[/underline]' not found."
msgstr "仓库 '[underline]${{path}}[/underline]' 未找到。"

#: ../rubisco/cli/main/arg_parser.py:96
msgid "Run rubisco in debug mode."
msgstr "以调试模式运行 rubisco。"

#: ../rubisco/cli/main/ktrigger.py:361
msgid "Running workflow: [white]${{name}}[/white] [black](${{id}})[/black]"
msgstr "正在运行工作流： [white]${{name}}[/white] [black](${{id}})[/black]"

#: ../rubisco/cli/main/ktrigger.py:342
msgid "Running: [white]${{name}}[/white] [black](${{id}})[/black]"
msgstr "正在运行： [white]${{name}}[/white] [black](${{id}})[/black]"

#: ../rubisco/lib/sqlite_strerror.py:139
msgid "SQL error or missing database."
msgstr "SQL 错误或缺少数据库。"

#: ../rubisco/lib/sqlite_strerror.py:337
msgid "SQLITE_OPEN_NOFOLLOW is used but the database file is a symlink."
msgstr "SQLITE_OPEN_NOFOLLOW 被使用，但数据库文件是一个符号链接。"

#: ../rubisco/lib/sqlite_strerror.py:293
msgid "SQLite detected an entry is or was missing from an index."
msgstr "SQLite 检测到一个条目在索引中缺失或已缺失。"

#: ../rubisco/lib/sqlite_strerror.py:254
msgid "SQLite is unable to obtain a read lock on a WAL mode database because the shared-memory file associated with that database is read-only."
msgstr "由于与该数据库关联的共享内存文件是只读的，SQLite 无法在 WAL 模式数据库上获取读锁。"

#: ../rubisco/cli/main/arg_parser.py:89
msgid "Save log to the log file."
msgstr "将日志保存到日志文件。"

#: ../rubisco/cli/output.py:282
msgid "See: ${{url}}"
msgstr "参见： ${{url}}"

#: ../rubisco/envutils/packages.py:412
msgid "Selected '${{name}}'."
msgstr "已选择 '${{name}}'。"

#: ../rubisco/cli/main/ktrigger.py:332
msgid "Selected mirror: ${{url}}"
msgstr "已选择镜像： ${{url}}"

#: ../rubisco/lib/process.py:130 ../rubisco/lib/process.py:189
msgid "Shell execution error."
msgstr "Shell 执行错误。"

#: ../rubisco/cli/main/builtin_cmds.py:55
msgid "Show Rubisco version."
msgstr "显示 Rubisco 版本。"

#: ../rubisco/cli/main/extman_cmds.py:325
msgid "Show extensions info with matching patterns."
msgstr "显示匹配模式的扩展信息。"

#: ../rubisco/cli/main/version_action.py:66
msgid "Show program's version number and exit."
msgstr "显示程序的版本号并退出。"

#: ../rubisco/cli/main/builtin_cmds.py:48
msgid "Show project information."
msgstr "显示项目信息。"

#: ../rubisco/cli/main/help_formatter.py:47
msgid "Show this help message and exit."
msgstr "显示此帮助消息并退出。"

#: ../rubisco/cli/main/arg_parser.py:103
msgid "Show usage."
msgstr "显示用法。"

#: ../rubisco/kernel/mirrorlist.py:256
msgid "Source '${{protocol}}/${{website}}/${{name}}' not found."
msgstr "源 '${{protocol}}/${{website}}/${{name}}' 未找到。"

#: ../rubisco/kernel/workflow.py:158
msgid "Step '${{step}}' failed: ${{exc}}"
msgstr "步骤 '${{step}}' 失败： ${{exc}}"

#: ../rubisco/kernel/workflow.py:732
msgid "Step id '${{step_id}}' is duplicated."
msgstr "步骤 '${{step_id}}' 的 ID 重复。"

#: ../rubisco/kernel/workflow.py:864
msgid "Step type '${{name}}' registered multiple times. This may cause unexpected behavior. It's unsafe."
msgstr "步骤类型 '${{name}}' 注册了多次。这可能导致意外行为。这是不安全的。"

#: ../rubisco/lib/sqlite_strerror.py:172
msgid "String or BLOB was too large."
msgstr "字符串或 BLOB 太大。"

#: ../rubisco/lib/exceptions.py:108
msgid "Subprocess return code is ${{retcode}}."
msgstr "子进程返回代码为 ${{retcode}}。"

#: ../rubisco/lib/exceptions.py:116
msgid "Subprocess return code is ${{retcode}}. It may be caused by command not found."
msgstr "子进程返回代码为 ${{retcode}}。可能是由于未找到命令。"

#: ../rubisco/lib/sqlite_strerror.py:137
msgid "Success."
msgstr "成功。"

#: ../rubisco/lib/archive/__init__.py:250
#: ../rubisco/lib/archive/__init__.py:513
msgid "Supported types are 'gz', 'bz2', 'xz', 'zip', '7z', 'tar', 'tar.gz', 'tar.bz2', 'tar.xz'. You can also use the 'tgz', 'txz' and 'tbz2'."
msgstr "我们支持的类型有 'gz', 'bz2', 'xz', 'zip', '7z', 'tar', 'tar.gz', 'tar.bz2', 'tar.xz'。您也可以使用 'tgz', 'txz' 和 'tbz2'。"

#: ../rubisco/envutils/packages.py:176
msgid "Tags must be a list of strings."
msgstr "标签必须是字符串列表。"

#: ../rubisco/envutils/packages.py:187
msgid "Tags must be lowercase and only contain 0-9, a-z, A-Z, '_' and '-'."
msgstr "标签必须是小写的，只能包含 0-9，a-z，A-Z，'_' 和 '-'。"

#: ../rubisco/cli/main/extman_cmds.py:174
msgid "Tags: ${{tags}}"
msgstr "标签： ${{tags}}"

#: ../rubisco/cli/main/ktrigger.py:282
msgid "Testing ${{host}} ... ${{status}}"
msgstr "正在测试 ${{host}} ... ${{status}}"

#: ../rubisco/envutils/env.py:127
msgid "The '${{path}}' is not a valid venv but exists.Please remove it and try again."
msgstr "'${{path}}' 存在，但不是有效的 venv 。请删除它并重试。"

#: ../rubisco/envutils/env.py:279
msgid "The PID '${{pid}}' is not valid. Maybe the process has already exited. Remove the lock file if you believe the process has already exited."
msgstr "PID '${{pid}}' 无效。可能进程已经退出。如果您相信进程已经退出，请手动删除锁文件。"

#: ../rubisco/lib/sqlite_strerror.py:443
msgid "The VFS is unable to determine a suitable directory in which to place temporary files."
msgstr "VFS 无法确定一个合适的目录来放置临时文件。"

#: ../rubisco/lib/sqlite_strerror.py:464
msgid "The checksum on a page of the database file is incorrect."
msgstr "数据库文件的页面校验和不正确。"

#: ../rubisco/kernel/workflow.py:361
msgid "The copy item must be a string."
msgstr "复制文件名必须是字符串类型。"

#: ../rubisco/lib/sqlite_strerror.py:447
msgid "The cygwin_conv_path() system call failed."
msgstr "cygwin_conv_path() 系统调用失败。"

#: ../rubisco/envutils/env.py:117
msgid "The database '${{path}}' is broken."
msgstr "数据库 '${{path}}' 损坏。"

#: ../rubisco/lib/sqlite_strerror.py:159
msgid "The database file has been corrupted."
msgstr "数据库文件已损坏。"

#: ../rubisco/lib/sqlite_strerror.py:147
msgid "The database file is locked."
msgstr "数据库文件被锁定。"

#: ../rubisco/lib/sqlite_strerror.py:325
msgid "The database is read-only because process does not have permission to create a journal file in the same directory as the database and the creation of a journal file is a prerequisite for writing."
msgstr "数据库是只读的，因为进程没有权限在与数据库相同的目录中创建日志文件，而创建日志文件是写入的先决条件。"

#: ../rubisco/lib/sqlite_strerror.py:170
msgid "The database schema changed."
msgstr "数据库模式已更改。"

#: ../rubisco/envutils/env.py:261
msgid "The environment '[underline]${{path}}[/underline]' is already locked by PID ${{pid}}. If you want to force unlock it, please remove the lock file '[underline]${{lockfile}}[/underline]' manually."
msgstr "环境 '[underline]${{path}}[/underline]' 已被 PID ${{pid}} 锁定。如果您想强制解锁，请手动删除锁文件 '[underline]${{lockfile}}[/underline]'。"

#: ../rubisco/envutils/env.py:385
msgid "The environment '[underline]${{path}}[/underline]' is locked by another thread (PID '${{pid}}', Thread '${{thread}}').Unlock request is ignored."
msgstr "环境 '[underline]${{path}}[/underline]' 被另一个线程锁定（PID '${{pid}}'，线程 '${{thread}}'）。解锁请求被忽略。"

#: ../rubisco/shared/extension.py:162
msgid "The extension '${{name}}' does not exist in workspace, user, or global extension directory."
msgstr "扩展 '${{name}}' 不存在于工作区、用户或全局扩展目录中。"

#: ../rubisco/shared/extension.py:220
msgid "The extension '[underline]${{path}}[/underline]' does not have an instance."
msgstr "扩展 '[underline]${{path}}[/underline]' 没有实例。"

#: ../rubisco/shared/extension.py:194
msgid "The extension path '[underline]${{path}}[/underline]' does not exist."
msgstr "扩展的路径 '[underline]${{path}}[/underline]' 不存在。"

#: ../rubisco/shared/extension.py:176
msgid "The extension path '[underline]${{path}}[/underline]' is not a directory."
msgstr "扩展的路径 '[underline]${{path}}[/underline]' 不是一个目录。"

#: ../rubisco/cli/main/ktrigger.py:776
msgid "The following extensions will be uninstalled from global ([underline]${{path}}[/underline]):"
msgstr "以下扩展将从全局 ([underline]${{path}}[/underline]) 卸载："

#: ../rubisco/cli/main/ktrigger.py:784
msgid "The following extensions will be uninstalled from user ([underline]${{path}}[/underline]):"
msgstr "以下扩展将从用户 ([underline]${{path}}[/underline]) 卸载："

#: ../rubisco/cli/main/ktrigger.py:792
msgid "The following extensions will be uninstalled from workspace ([underline]${{path}}[/underline]):"
msgstr "以下扩展将从工作区 ([underline]${{path}}[/underline]) 卸载："

#: ../rubisco/envutils/packages.py:531 ../rubisco/envutils/packages.py:588
msgid "The higher version of '${{name}}' extension is already installed."
msgstr "已安装了 '${{name}}' 扩展的更高版本。"

#: ../rubisco/lib/sqlite_strerror.py:275
msgid "The historical snapshot is no longer available."
msgstr "历史快照不再可用。"

#: ../rubisco/envutils/env.py:311
msgid "The lock file '[underline]${{lockfile}}[/underline]' is broken."
msgstr "锁文件 '[underline]${{lockfile}}[/underline]' 损坏。"

#: ../rubisco/kernel/project_config.py:165
msgid "The minimum version of rubisco required by the project '[underline]${{name}}[/underline]' is '[underline]${{version}}[/underline]'."
msgstr "项目 '[underline]${{name}}[/underline]' 所需的 rubisco 最低版本为 '[underline]${{version}}[/underline]'。"

#: ../rubisco/kernel/workflow.py:244
msgid "The paths must be a list of strings."
msgstr "多个路径必须是一个字符串列表。"

#: ../rubisco/kernel/workflow.py:422
msgid "The remove item must be a string."
msgstr "删除项必须是一个字符串。"

#: ../rubisco/envutils/packages.py:519 ../rubisco/envutils/packages.py:576
msgid "The same version of '${{name}}' extension is already installed."
msgstr "已安装了 '${{name}}' 扩展的相同版本。"

#: ../rubisco/lib/sqlite_strerror.py:264
msgid "The schema of the sqlite_sequence table is corrupt."
msgstr "sqlite_sequence 表的模式损坏。"

#: ../rubisco/kernel/workflow.py:211
msgid "The shell command list must be a list of strings."
msgstr "shell 命令列表必须是一个字符串列表。"

#: ../rubisco/kernel/workflow.py:947
msgid "The suffix of '[underline]${{path}}[/underline]' is invalid."
msgstr "文件 '[underline]${{path}}[/underline]' 的后缀无效。"

#: ../rubisco/kernel/workflow.py:770
msgid "The type of step '${{step}}'[black](${{step_id}})[/black] in workflow '${{workflow}}'[black](${{workflow_id}})[/black] is not provided and could not be inferred."
msgstr "工作流 '${{workflow}}'[black](${{workflow_id}})[/black] 中的步骤 '${{step}}'[black](${{step_id}})[/black] 的类型未被提供，且无法推断。"

#: ../rubisco/lib/sqlite_strerror.py:450
msgid "The underlying operating system reported and error on the SQLITE_FCNTL_BEGIN_ATOMIC_WRITE file-control."
msgstr "操作系统在 SQLITE_FCNTL_BEGIN_ATOMIC_WRITE 文件控制上报告了错误。"

#: ../rubisco/lib/sqlite_strerror.py:455
msgid "The underlying operating system reported and error on the SQLITE_FCNTL_COMMIT_ATOMIC_WRITE file-control."
msgstr "操作系统在 SQLITE_FCNTL_COMMIT_ATOMIC_WRITE 文件控制上报告了错误。"

#: ../rubisco/lib/sqlite_strerror.py:460
msgid "The underlying operating system reported and error on the SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE file-control."
msgstr "操作系统在 SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE 文件控制上报告了错误。"

#: ../rubisco/lib/variable.py:661
msgid "The value of key ${{key}} needs to be ${{type}} instead of ${{value_type}}."
msgstr "键 ${{key}} 的值需要是 ${{type}} 类型而不是 ${{value_type}} 。"

#: ../rubisco/lib/sqlite_strerror.py:432
msgid "The xDelete method on the sqlite3_vfs object failed because the file being deleted does not exist."
msgstr "sqlite3_vfs 对象上的 xDelete 方法失败，因为要删除的文件不存在。"

#: ../rubisco/shared/extension.py:168
msgid "Try to load the extension as a path."
msgstr "尝试将扩展作为路径加载。"

#: ../rubisco/lib/archive/__init__.py:224
#: ../rubisco/lib/archive/__init__.py:486
msgid "Unable to determine compression type of '[underline]${{path}}[/underline]'"
msgstr "无法确定 '[underline]${{path}}[/underline]' 的压缩类型"

#: ../rubisco/lib/sqlite_strerror.py:163
msgid "Unable to open the database file."
msgstr "无法打开数据库文件。"

#: ../rubisco/cli/main/project_config.py:120
msgid "Undefined command or hook ${{name}}"
msgstr "未定义的命令或钩子 ${{name}}"

#: ../rubisco/cli/main/extman_cmds.py:447
msgid "Uninstall extensions in global."
msgstr "卸载全局扩展。"

#: ../rubisco/cli/main/extman_cmds.py:438
msgid "Uninstall extensions in user."
msgstr "卸载用户扩展。"

#: ../rubisco/cli/main/extman_cmds.py:429
msgid "Uninstall extensions in workspace."
msgstr "卸载工作区扩展。"

#: ../rubisco/cli/main/extman_cmds.py:410
msgid "Uninstall extensions with matching patterns."
msgstr "卸载匹配模式的扩展。"

#: ../rubisco/cli/main/ktrigger.py:634
msgid "Uninstalling extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from global ([underline]${{path}}[/underline]) ..."
msgstr "正在从全局卸载扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/main/ktrigger.py:649
msgid "Uninstalling extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from user ([underline]${{path}}[/underline]) ..."
msgstr "正在从用户卸载扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/main/ktrigger.py:664
msgid "Uninstalling extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from workspace ([underline]${{path}}[/underline]) ..."
msgstr "正在从工作区卸载扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] ([underline]${{path}}[/underline]) ..."

#: ../rubisco/envutils/env.py:256 ../rubisco/kernel/mirrorlist.py:203
#: ../rubisco/lib/l10n.py:71
msgid "Unknown"
msgstr "未知"

#: ../rubisco/lib/sqlite_strerror.py:471
msgid "Unknown error code."
msgstr "未知错误代码。"

#: ../rubisco/cli/output.py:251
msgid "Unknown error."
msgstr "未知错误。"

#: ../rubisco/kernel/workflow.py:753
msgid "Unknown step type: '${{step_type}}' of step '${{step_name}}'. Please check the workflow."
msgstr "未知的步骤类型: '${{step_type}}' 的步骤 '${{step_name}}'。请检查工作流。"

#: ../rubisco/lib/archive/__init__.py:246
#: ../rubisco/lib/archive/__init__.py:509
msgid "Unsupported compression type: '${{type}}'"
msgstr "不支持的压缩类型: '${{type}}'"

#: ../rubisco/cli/main/ktrigger.py:238
msgid "Updating Git repository '[underline]${{path}}[/underline]'(${{branch}}) ..."
msgstr "正在更新 Git 仓库 '[underline]${{path}}[/underline]'(${{branch}}) ..."

#: ../rubisco/cli/main/ktrigger.py:706
msgid "Upgrading extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from global ([underline]${{path}}[/underline]) ..."
msgstr "正在升级扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 从全局 ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/main/ktrigger.py:721
msgid "Upgrading extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from user ([underline]${{path}}[/underline]) ..."
msgstr "正在升级扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 从用户 ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/main/ktrigger.py:736
msgid "Upgrading extension [green]${{name}}[/green]:[cyan]${{version}}[/cyan] from workspace ([underline]${{path}}[/underline]) ..."
msgstr "正在升级扩展 [green]${{name}}[/green]:[cyan]${{version}}[/cyan] 从工作区 ([underline]${{path}}[/underline]) ..."

#: ../rubisco/cli/main/help_formatter.py:53
msgid "Usage:"
msgstr "用法："

#: ../rubisco/cli/main/extman_cmds.py:139
msgid "Version: [cyan]${{ver}}[/cyan]"
msgstr "版本： [cyan]${{ver}}[/cyan]"

#: ../rubisco/lib/sqlite_strerror.py:249
msgid "Virtual table implementations cannot complete the current operation because of locks held by other threads or processes."
msgstr "由于其他线程或进程持有的锁，虚拟表实现无法完成当前操作。"

#: ../rubisco/envutils/env.py:204
msgid "Waiting for the environment to be unlocked ('${{lock_file}}'): ${{seconds}} seconds."
msgstr "等待 venv 解锁 ('${{lock_file}}'): ${{seconds}} 秒。"

#: ../rubisco/kernel/workflow.py:952
msgid "We only support '.json', '.json5', '.yaml', '.yml'."
msgstr "我们只支持 '.json', '.json5', '.yaml', '.yml'。"

#: ../rubisco/cli/main/ktrigger.py:373
msgid "Workflow '${{name}}' finished."
msgstr "工作流 '${{name}}' 完成。"

#: ../rubisco/kernel/workflow.py:910
msgid "Workflow running failed: ${{exc}}"
msgstr "工作流运行失败: ${{exc}}"

#: ../rubisco/kernel/workflow.py:683
msgid "Workflow variables must be a list of name and value."
msgstr "工作流变量必须是名称和值的列表。"

#: ../rubisco/cli/main/project_config.py:75
#: ../rubisco/cli/main/project_config.py:140
msgid "Working directory '[underline]${{path}}[/underline]' not a rubisco project."
msgstr "工作目录 '[underline]${{path}}[/underline]' 不是一个 rubisco 项目。"

#: ../rubisco/envutils/pip.py:78
msgid "You are installing a extension to the global environment. Please make sure that you have the right permissions."
msgstr "您正在安装一个扩展到全局环境。请确保您具有正确的权限。"

#: ../rubisco/envutils/env_db.py:141
msgid "[SQLite3 Errorcode ${{codename}}(${{code}})]: ${{msg}}"
msgstr "[SQLite3 错误代码 ${{codename}}(${{code}})]: ${{msg}}"

#: ../rubisco/cli/main/ktrigger.py:456
msgid "[dark_orange]Configuration:[/dark_orange] [underline]${{path}}[/underline]"
msgstr "[dark_orange]配置：[/dark_orange] [underline]${{path}}[/underline]"

#: ../rubisco/cli/main/ktrigger.py:490
msgid "[dark_orange]Description:[/dark_orange] ${{desc}}"
msgstr "[dark_orange]描述：[/dark_orange] ${{desc}}"

#: ../rubisco/cli/main/ktrigger.py:495
msgid "[dark_orange]Hooks:[/dark_orange]"
msgstr "[dark_orange]钩子：[/dark_orange]"

#: ../rubisco/cli/main/ktrigger.py:484
msgid "[dark_orange]License:[/dark_orange] ${{license}}"
msgstr "[dark_orange]许可证：[/dark_orange] ${{license}}"

#: ../rubisco/cli/main/ktrigger.py:478
msgid "[dark_orange]Maintainer:[/dark_orange] ${{maintainer}}"
msgstr "[dark_orange]维护者：[/dark_orange] ${{maintainer}}"

#: ../rubisco/cli/main/ktrigger.py:449
msgid "[dark_orange]Project:[/dark_orange] ${{name}}"
msgstr "[dark_orange]项目：[/dark_orange] ${{name}}"

#: ../rubisco/cli/main/ktrigger.py:437
msgid "[dark_orange]Rubisco CLI Language:[/dark_orange] '${{locale}}' '${{charset}}' '${{language_name}}'"
msgstr "[dark_orange]Rubisco CLI 语言：[/dark_orange] '${{locale}}' '${{charset}}' '${{language_name}}'"

#: ../rubisco/cli/main/ktrigger.py:465
msgid "[dark_orange]Version:[/dark_orange] v[white]${{version}}[/white]"
msgstr "[dark_orange]版本：[/dark_orange] v[white]${{version}}[/white]"

#: ../rubisco/cli/output.py:223
msgid "[italic][magenta]Hint:[/magenta] ${{msg}}[/italic]"
msgstr "[italic][magenta]提示：[/magenta] ${{msg}}[/italic]"

#: ../rubisco/cli/main/ktrigger.py:303
msgid "[red]Canceled[/red]"
msgstr "[red]已取消[/red]"

#: ../rubisco/cli/output.py:195
msgid "[red]Error: ${{msg}}[/red]"
msgstr "[red]错误： ${{msg}}[/red]"

#: ../rubisco/cli/main/ktrigger.py:305
msgid "[red]Failed[/red]"
msgstr "[red]失败[/red]"

#: ../rubisco/envutils/packages.py:236
msgid "[underline]${{path}}[/underline] Error when opening 'rubisco.json': '${{msg}}'."
msgstr "[underline]${{path}}[/underline] 打开 'rubisco.json' 时出错: '${{msg}}'。"

#: ../rubisco/envutils/packages.py:343
msgid "[underline]${{path}}[/underline] already exists in the filesystem."
msgstr "[underline]${{path}}[/underline] 已经存在于文件系统中。"

#: ../rubisco/envutils/packages.py:214
msgid "[underline]${{path}}[/underline] is not a valid Rubisco extension package. (Zip file)"
msgstr "[underline]${{path}}[/underline] 不是一个有效的 Rubisco 扩展包。 (Zip 文件)"

#: ../rubisco/envutils/packages.py:245
msgid "[underline]${{path}}[/underline] package configuration file is missing a required key: '${{key}}'."
msgstr "[underline]${{path}}[/underline] 软件包配置文件缺少一个必需的键: '${{key}}'。"

#: ../rubisco/envutils/packages.py:224
msgid "[underline]${{path}}[/underline] package configuration file is not a valid JSON5 file."
msgstr "[underline]${{path}}[/underline] 软件包配置文件不是一个有效的 JSON5 文件。"

#: ../rubisco/cli/main/ktrigger.py:147
msgid "[yellow]Compressing[/yellow]"
msgstr "[yellow]压缩中[/yellow]"

#: ../rubisco/cli/main/ktrigger.py:143
msgid "[yellow]Downloading[/yellow]"
msgstr "[yellow]下载中[/yellow]"

#: ../rubisco/cli/main/ktrigger.py:145
msgid "[yellow]Extracting[/yellow]"
msgstr "[yellow]解压中[/yellow]"

#: ../rubisco/cli/input.py:71
msgid "[yellow]Invalid input. Please enter '[green]Y[/green]' or '[red]N[/red]'."
msgstr "无效的输入。请输入 '[green]Y[/green]' 或 '[red]N[/red]'。"

#: ../rubisco/cli/main/ktrigger.py:149
msgid "[yellow]Processing[/yellow]"
msgstr "[yellow]处理中[/yellow]"

#: ../rubisco/cli/main/ktrigger.py:295 ../rubisco/cli/main/ktrigger.py:317
msgid "[yellow]Testing[/yellow] ..."
msgstr "[yellow]测试中[/yellow] ..."

#: ../rubisco/kernel/project_config.py:179
#: ../rubisco/kernel/project_config.py:185
msgid "[yellow]Unknown[/yellow]"
msgstr "[yellow]未知[/yellow]"

#: ../rubisco/cli/output.py:208
msgid "[yellow]Warning: ${{msg}}[/yellow]"
msgstr "[yellow]警告： ${{msg}}[/yellow]"

#: /usr/lib/python3.12/argparse.py:2044
#, python-format
msgid "ambiguous option: %(option)s could match %(matches)s"
msgstr "不明确的选项: %(option)s 可能匹配 %(matches)s"

#: /usr/lib/python3.12/argparse.py:1337
#, python-format
msgid "argument \"-\" with mode %r"
msgstr "参数 \"-\" 的模式 %r"

#: /usr/lib/python3.12/argparse.py:798
#, python-format
msgid "argument %(argument_name)s: %(message)s"
msgstr "参数 %(argument_name)s: %(message)s"

#: /usr/lib/python3.12/argparse.py:1346
#, python-format
msgid "can't open '%(filename)s': %(error)s"
msgstr "无法打开 '%(filename)s': %(error)s"

#: /usr/lib/python3.12/argparse.py:1868
msgid "cannot have multiple subparser arguments"
msgstr "不能有多个子解析器参数"

#: /usr/lib/python3.12/argparse.py:1555
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr "无法合并操作 - 两个组都命名为 %r"

#: /usr/lib/python3.12/argparse.py:1671
#, python-format
msgid "conflicting option string: %s"
msgid_plural "conflicting option strings: %s"
msgstr[0] "冲突的选项字符串: %s"
msgstr[1] "冲突的选项字符串: %s"

#: /usr/lib/python3.12/argparse.py:1241
#, python-format
msgid "conflicting subparser alias: %s"
msgstr "冲突的子解析器别名: %s"

#: /usr/lib/python3.12/argparse.py:1237
#, python-format
msgid "conflicting subparser: %s"
msgstr "冲突的子解析器: %s"

#: ../rubisco/lib/sqlite_strerror.py:311
msgid "cygwin_conv_path() failed."
msgstr "cygwin_conv_path() 失败。"

#: /usr/lib/python3.12/argparse.py:1636
#, python-format
msgid "dest= is required for options like %r"
msgstr "对于 %r 这样的选项，需要 dest="

#: /usr/lib/python3.12/argparse.py:2309
#, python-format
msgid "expected %s argument"
msgid_plural "expected %s arguments"
msgstr[0] "预期 %s 个参数"
msgstr[1] "预期 %s 个参数"

#: /usr/lib/python3.12/argparse.py:2305
msgid "expected at least one argument"
msgstr "预期至少一个参数"

#: /usr/lib/python3.12/argparse.py:2304
msgid "expected at most one argument"
msgstr "预期最多一个参数"

#: /usr/lib/python3.12/argparse.py:2303
msgid "expected one argument"
msgstr "预期一个参数"

#: ../rubisco/cli/main/extman_cmds.py:62
msgid "foreign-package"
msgstr "外部包"

#: ../rubisco/cli/main/extman_cmds.py:56
msgid "global"
msgstr "全局"

#: /usr/lib/python3.12/argparse.py:2076 /usr/lib/python3.12/argparse.py:2108
#, python-format
msgid "ignored explicit argument %r"
msgstr "忽略显式参数 %r"

#: /usr/lib/python3.12/argparse.py:2571
#, python-format
msgid "invalid %(type)s value: %(value)r"
msgstr "无效的 %(type)s 值: %(value)r"

#: /usr/lib/python3.12/argparse.py:2586
#, python-format
msgid "invalid choice: %(value)r (choose from %(choices)s)"
msgstr "无效的选择: %(value)r (可选项为 %(choices)s)"

#: /usr/lib/python3.12/argparse.py:1653
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr "无效的 conflict_resolution 值: %r"

#: /usr/lib/python3.12/argparse.py:1618
#, python-format
msgid "invalid option string %(option)r: must start with a character %(prefix_chars)r"
msgstr "无效的选项字符串 %(option)r: 必须以字符 %(prefix_chars)r 开头"

#: /usr/lib/python3.12/argparse.py:1745
msgid "mutually exclusive arguments must be optional"
msgstr "互斥参数必须是可选的"

#: /usr/lib/python3.12/argparse.py:2025
#, python-format
msgid "not allowed with argument %s"
msgstr "不允许与参数 %s 一起使用"

#: /usr/lib/python3.12/argparse.py:2259
#, python-format
msgid "one of the arguments %s is required"
msgstr "需要其中一个参数 %s"

#: /usr/lib/python3.12/argparse.py:1822
msgid "options"
msgstr "选项"

#: /usr/lib/python3.12/argparse.py:1821
msgid "positional arguments"
msgstr "位置参数"

#: /usr/lib/python3.12/argparse.py:1175
msgid "show program's version number and exit"
msgstr "显示程序的版本号并退出"

#: /usr/lib/python3.12/argparse.py:1837
msgid "show this help message and exit"
msgstr "显示此帮助消息并退出"

#: /usr/lib/python3.12/argparse.py:1874
msgid "subcommands"
msgstr "子命令"

#: /usr/lib/python3.12/argparse.py:2244
#, python-format
msgid "the following arguments are required: %s"
msgstr "需要以下参数: %s"

#: /usr/lib/python3.12/argparse.py:2419
#, python-format
msgid "unexpected option string: %s"
msgstr "意外的选项字符串: %s"

#: ../rubisco/cli/main/extman_cmds.py:63
msgid "unknown"
msgstr "未知"

#: /usr/lib/python3.12/argparse.py:1276
#, python-format
msgid "unknown parser %(parser_name)r (choices: %(choices)s)"
msgstr "未知的解析器 %(parser_name)r (可选项: %(choices)s)"

#: /usr/lib/python3.12/argparse.py:1920 /usr/lib/python3.12/argparse.py:2473
#, python-format
msgid "unrecognized arguments: %s"
msgstr "未识别的参数：%s"

#: /usr/lib/python3.12/argparse.py:313
msgid "usage: "
msgstr "用法："

#: ../rubisco/cli/main/extman_cmds.py:58
msgid "user"
msgstr "用户"

#: ../rubisco/cli/main/extman_cmds.py:60
msgid "workspace"
msgstr "工作区"
